# Generated by Django 4.2.3 on 2023-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('thumbleimage', models.ImageField(blank=True, null=True, upload_to='blogpic')),
                ('blogimg', models.ImageField(blank=True, null=True, upload_to='blogpic')),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
