# Generated by Django 4.2.3 on 2023-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('fimage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
                ('simage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
                ('timage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
                ('forthimage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
